/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: "#083B49", foreground: "#FFFFFF" },
        secondary: { DEFAULT: "#2E5984", foreground: "#FFFFFF" },
        accent: { DEFAULT: "#E67E22", foreground: "#FFFFFF" },
        background: "#FAFBFC",
        foreground: "#083B49",
        card: { DEFAULT: "#F4F6F8", foreground: "#083B49" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#083B49" },
        muted: { DEFAULT: "#E1E8ED", foreground: "#5D6D7E" },
        border: "#E1E8ED",
        input: "#E1E8ED",
        ring: "#083B49",
        success: { DEFAULT: "#27AE60", foreground: "#FFFFFF" },
        warning: { DEFAULT: "#F39C12", foreground: "#FFFFFF" },
        error: { DEFAULT: "#E74C3C", foreground: "#FFFFFF" },
        destructive: { DEFAULT: "#E74C3C", foreground: "#FFFFFF" },
        "golden-opportunity": "#E8B931",
        "action-catalyst": "#FF6B35",
        "verification-green": "#2E7D32",
        "authority-charcoal": "#1A1A1A",
        "intelligent-gray": "#6B7280",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Source Sans Pro", "sans-serif"],
        cta: ["Poppins", "sans-serif"],
        accent: ["JetBrains Mono", "monospace"],
        sans: ["Source Sans Pro", "sans-serif"],
      },
      spacing: {
        base: "8px",
        xs: "13px",
        sm: "21px",
        md: "34px",
        lg: "55px",
        xl: "89px",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
      boxShadow: {
        card: "0 2px 8px rgba(27, 54, 93, .08)",
        modal: "0 4px 16px rgba(27, 54, 93, .12)",
        hover: "0 4px 20px rgba(0, 0, 0, .1)",
        elevated: "0 8px 40px rgba(0, 0, 0, .15)",
      },
    },
  },
  plugins: [],
};
