import { useEffect, useState } from "react";
import { CheckCircle2, ChevronDown, Download, Eye, FileSpreadsheet, Filter, Plus, Search, Settings2, Trash2, Upload, X } from "lucide-react";
import DashboardLayout from "../components/layout/DashboardLayout";
import { api, download } from "../lib/api";
import { can } from "../lib/permissions";
import { useToast } from "../components/toast";

const COLUMNS = [
  ["group_name","Group Name"],["primary_contact_number","Primary Contact Number"],["primary_contact_name","Primary Contact Name"],
  ["primary_contact_designation","Primary Contact Designation"],["grades","Grades"],["application","Application"],["pan","PAN"],
  ["gst_slab","GST Slab"],["state","State"],["group_tag","Group Tag"],["reference","Reference"],["sub_application","Sub Application"],
  ["remark","Remark"],["hsn_code","HSN Code"],["lead_manager","Lead Manager"],["parent_location","Parent Location"]
];
const EMPTY={group_name:"",pan:"",primary_contact_name:"",primary_contact_number:"",primary_contact_designation:"",gst_slab:"",state:"",group_tag:"",reference:"",parent_location:"",remark:"",lead_manager:"",lead_type:"",monthly_consumption:"",call_date:"",next_call_date:"",call_remark:"",profile_shared:false,quote_shared:false,order_status:"Prospect",credit_interest:""};
const TABS=["Overview","Custom Fields","Contacts","Locations","CRM Information","Transactions","Activity Timeline","Finance","Documents"];
const show=(v)=>v===null||v===undefined||v===""?"—":String(v);

function Field({label,name,form,setForm,type="text",required=false,wide=false}) { return <label className={wide?"sm:col-span-2":""}><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}</span>{type==="textarea"?<textarea value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})} className="min-h-20 w-full rounded-md border border-input p-2 text-sm"/>:<input required={required} type={type} value={form[name]??""} onChange={e=>setForm({...form,[name]:type==="checkbox"?e.target.checked:e.target.value})} checked={type==="checkbox"?!!form[name]:undefined} className={type==="checkbox"?"h-4 w-4":"h-10 w-full rounded-md border border-input px-3 text-sm"}/>}</label> }

export default function Clients(){
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[sort,setSort]=useState("created_at"),[direction,setDirection]=useState("desc");
 const [visible,setVisible]=useState(()=>COLUMNS.map(c=>c[0])),[columnsOpen,setColumnsOpen]=useState(false),[formOpen,setFormOpen]=useState(false),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false);
 const [selected,setSelected]=useState(null),[tab,setTab]=useState("Overview"),[contactForm,setContactForm]=useState(null),[locationForm,setLocationForm]=useState(null); const toast=useToast();
 const [uploadOpen,setUploadOpen]=useState(false),[uploadFile,setUploadFile]=useState(null),[uploadState,setUploadState]=useState("idle"),[uploadResult,setUploadResult]=useState(null);
 const [uploadAnalysis,setUploadAnalysis]=useState(null);
 const [filtersOpen,setFiltersOpen]=useState(false),[filters,setFilters]=useState({state:"",group_tag:"",lead_manager:"",order_status:""});
 const canDelete=can("delete"),canExport=can("export"),canCreate=can("create");
 async function load(){setLoading(true);try{const q=new URLSearchParams({search,sort,direction,limit:"100"});Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));const result=await api(`/buyers?${q}`);setRows(result.data);setTotal(result.total);}catch(e){toast(e.message,"error");}finally{setLoading(false)}}
 // Reload the server-side result when the active search/sort changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id)},[search,sort,direction,filters.state,filters.group_tag,filters.lead_manager,filters.order_status]);
 async function openBuyer(id){try{setSelected(await api(`/buyers/${id}`));setTab("Overview")}catch(e){toast(e.message,"error")}}
 async function save(e){e.preventDefault();setSaving(true);try{const payload={...form,monthly_consumption:form.monthly_consumption===""?null:Number(form.monthly_consumption)};const buyer=await api("/buyers",{method:"POST",body:JSON.stringify(payload)});setFormOpen(false);setForm(EMPTY);toast("Buyer Group created.");load();openBuyer(buyer.id)}catch(e){toast(e.message,"error")}finally{setSaving(false)}}
 function sortBy(key){if(sort===key)setDirection(direction==="asc"?"desc":"asc");else{setSort(key);setDirection("asc")}}
 function exportCsv(){const cols=COLUMNS.filter(c=>visible.includes(c[0]));const csv=[cols.map(c=>c[1]),...rows.map(r=>cols.map(c=>r[c[0]]??""))].map(line=>line.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="buyers-filtered.csv";a.click();URL.revokeObjectURL(a.href)}
 async function addChild(kind,data){try{await api(`/buyers/${selected.id}/${kind}`,{method:"POST",body:JSON.stringify(data)});toast(`${kind==="contacts"?"Contact":"Location"} added.`);setSelected(await api(`/buyers/${selected.id}`));setContactForm(null);setLocationForm(null)}catch(e){toast(e.message,"error")}}
 function chooseUpload(file){if(!file)return;if(!file.name.toLowerCase().endsWith(".xlsx")){toast("Please select an .xlsx file.","error");return}setUploadFile(file);setUploadResult(null);setUploadAnalysis(null);setUploadState("ready")}
 async function analyzeBuyers(){const body=new FormData();body.append("file",uploadFile);setUploadState("analyzing");try{const analysis=await api("/buyers/bulk-upload/analyze",{method:"POST",body});setUploadAnalysis(analysis);setUploadState("analyzed")}catch(e){setUploadState("failed");toast(e.message,"error")}}
 async function uploadBuyers(){const body=new FormData();body.append("file",uploadFile);setUploadState("uploading");try{await new Promise(resolve=>setTimeout(resolve,350));setUploadState("processing");const result=await api("/buyers/bulk-upload",{method:"POST",body});setUploadResult(result);setUploadState("completed");toast("Buyer directory synced successfully.");load()}catch(e){setUploadState("failed");toast(e.message,"error")}}
 function closeUpload(){if(["analyzing","uploading","processing"].includes(uploadState))return;setUploadOpen(false);setUploadFile(null);setUploadResult(null);setUploadAnalysis(null);setUploadState("idle")}
 async function removeBuyer(row){if(!confirm(`Delete buyer group “${row.group_name}”? This cannot be undone.`))return;try{await api(`/buyers/${row.id}`,{method:"DELETE"});toast("Buyer group deleted.");if(selected?.id===row.id)setSelected(null);load()}catch(e){toast(e.message,"error")}}
 return <DashboardLayout title="Buyers"><div className="space-y-4">
  <section className="flex flex-col gap-3 rounded-xl border border-border bg-white p-5 shadow-card lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold">Buyer Groups</h2><p className="text-sm text-muted-foreground">One Buyer Group per PAN · {total} records</p></div><div className="flex flex-wrap gap-2">{canExport&&<button onClick={exportCsv} className="flex h-9 items-center gap-2 rounded-md border px-3 text-sm"><Download className="w-4"/>Export filtered</button>}{canCreate&&<><button onClick={()=>setUploadOpen(true)} className="flex h-9 items-center gap-2 rounded-md border border-accent px-3 text-sm font-medium text-accent"><Upload className="w-4"/>Bulk Upload</button><button onClick={()=>setFormOpen(true)} className="flex h-9 items-center gap-2 rounded-md bg-accent px-3 text-sm font-medium text-accent-foreground"><Plus className="w-4"/>Add Buyer Group</button></>}</div></section>
  <section className="overflow-hidden rounded-xl border border-border bg-white shadow-card"><div className="flex flex-wrap items-center gap-2 border-b p-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 w-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search group, PAN, contact, state, tag…" className="h-9 w-full rounded-md border pl-9 pr-3 text-sm"/></div><button onClick={()=>setFiltersOpen(!filtersOpen)} className={`flex h-9 items-center gap-2 rounded-md border px-3 text-sm ${Object.values(filters).some(Boolean)?"border-accent bg-accent/10":""}`}><Filter className="w-4"/>Filters{Object.values(filters).filter(Boolean).length>0&&<span className="rounded-full bg-accent px-1.5 text-xs">{Object.values(filters).filter(Boolean).length}</span>}</button><div className="relative"><button onClick={()=>setColumnsOpen(!columnsOpen)} className="flex h-9 items-center gap-2 rounded-md border px-3 text-sm"><Settings2 className="w-4"/>Columns<ChevronDown className="w-3"/></button>{columnsOpen&&<div className="absolute right-0 z-20 mt-1 max-h-80 w-64 overflow-auto rounded-lg border bg-white p-2 shadow-lg">{COLUMNS.map(([key,label])=><label key={key} className="flex gap-2 p-2 text-sm"><input type="checkbox" checked={visible.includes(key)} onChange={()=>setVisible(visible.includes(key)?visible.filter(x=>x!==key):[...visible,key])}/>{label}</label>)}</div>}</div></div>
   {filtersOpen&&<div className="grid gap-3 border-b bg-card p-4 sm:grid-cols-2 lg:grid-cols-5">{[["State","state"],["Group Tag","group_tag"],["Lead Manager","lead_manager"],["Order Status","order_status"]].map(([label,key])=><label key={key}><span className="mb-1 block text-xs font-medium">{label}</span><input value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})} placeholder={`Filter by ${label.toLowerCase()}`} className="h-9 w-full rounded border bg-white px-3 text-sm"/></label>)}<div className="flex items-end"><button onClick={()=>setFilters({state:"",group_tag:"",lead_manager:"",order_status:""})} className="h-9 rounded border bg-white px-3 text-sm">Clear all</button></div></div>}
   <div className="max-h-[65vh] overflow-auto"><table className="min-w-max text-left text-sm"><thead className="sticky top-0 z-10 bg-card text-xs uppercase text-muted-foreground"><tr>{COLUMNS.filter(c=>visible.includes(c[0])).map(([key,label])=><th key={key} onClick={()=>sortBy(key)} className={`${key==="group_name"?"sticky left-0 z-20 bg-card":""} cursor-pointer whitespace-nowrap border-r px-4 py-3`}>{label}{sort===key?(direction==="asc"?" ↑":" ↓"):""}</th>)}<th className="px-4">Actions</th></tr></thead><tbody>{loading?<tr><td className="p-10 text-center" colSpan={visible.length+1}>Loading…</td></tr>:rows.map(r=><tr key={r.id} className="border-t hover:bg-card/60">{COLUMNS.filter(c=>visible.includes(c[0])).map(([key])=><td key={key} className={`${key==="group_name"?"sticky left-0 bg-white font-medium":""} max-w-64 truncate whitespace-nowrap border-r px-4 py-3`}>{show(r[key])}</td>)}<td className="flex gap-1 px-4"><button title="View buyer" onClick={()=>openBuyer(r.id)} className="rounded p-2 text-primary hover:bg-card"><Eye className="w-4"/></button>{canDelete&&<button title="Delete buyer" onClick={()=>removeBuyer(r)} className="rounded p-2 text-red-600 hover:bg-red-50"><Trash2 className="w-4"/></button>}</td></tr>)}</tbody></table></div>
  </section>
 </div>
 {formOpen&&<Modal title="Add Buyer Group" close={()=>setFormOpen(false)}><form onSubmit={save}><BuyerFields form={form} setForm={setForm}/><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setFormOpen(false)} className="h-10 rounded-md border px-4">Cancel</button><button disabled={saving} className="h-10 rounded-md bg-accent px-4 font-medium text-accent-foreground">{saving?"Saving…":"Save Buyer"}</button></div></form></Modal>}
 {uploadOpen&&<Modal title="Bulk Upload Buyer Data" close={closeUpload} locked={["analyzing","uploading","processing"].includes(uploadState)}><BulkUpload file={uploadFile} state={uploadState} analysis={uploadAnalysis} result={uploadResult} choose={chooseUpload} analyze={analyzeBuyers} proceed={uploadBuyers} close={closeUpload}/></Modal>}
 {selected&&<Profile buyer={selected} tab={tab} setTab={setTab} close={()=>setSelected(null)} contactForm={contactForm} setContactForm={setContactForm} locationForm={locationForm} setLocationForm={setLocationForm} addChild={addChild}/>} </DashboardLayout>
}

function BuyerFields({form,setForm}){return <div className="grid gap-4 sm:grid-cols-2"><Field label="Group Name" name="group_name" required form={form} setForm={setForm}/><Field label="PAN (one Group = one PAN)" name="pan" required form={form} setForm={setForm}/><Field label="Primary Contact Name" name="primary_contact_name" form={form} setForm={setForm}/><Field label="Primary Contact Number" name="primary_contact_number" form={form} setForm={setForm}/><Field label="Primary Contact Designation" name="primary_contact_designation" form={form} setForm={setForm}/>{[["GST Slab","gst_slab"],["State","state"],["Group Tag","group_tag"],["Reference","reference"],["Lead Manager","lead_manager"],["Parent Location","parent_location"],["Lead Type","lead_type"],["Monthly Consumption","monthly_consumption"],["Call Date","call_date","date"],["Next Call Date","next_call_date","date"],["Order Status","order_status"],["Credit Interest","credit_interest"]].map(([l,n,t])=><Field key={n} label={l} name={n} type={t} form={form} setForm={setForm}/>)}<Field label="Remark" name="remark" type="textarea" wide form={form} setForm={setForm}/><Field label="Call Remark" name="call_remark" type="textarea" wide form={form} setForm={setForm}/></div>}
function Modal({title,close,children,locked=false}){return <div className="fixed inset-0 z-50 grid place-items-center bg-primary/40 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h3 className="text-lg font-semibold">{title}</h3><button disabled={locked} className={locked?"cursor-not-allowed opacity-30":""} onClick={close}><X className="w-5"/></button></div>{children}</div></div>}

function saveInvalidReport(analysis){if(!analysis?.invalidReport)return;const bytes=Uint8Array.from(atob(analysis.invalidReport),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a");a.href=url;a.download="buyer-upload-invalid-rows.xlsx";a.click();URL.revokeObjectURL(url)}
function BulkUpload({file,state,analysis,result,choose,analyze,proceed,close}){const busy=["analyzing","uploading","processing"].includes(state);return <div className="space-y-5">
 <div><p className="text-sm text-muted-foreground">Upload the monthly GST Excel. PAN creates or updates a Group, GSTIN creates or updates a Location, and phone number identifies the Person.</p><button onClick={()=>download("/buyers/bulk-upload/template","buyer-gst-upload-template.xlsx")} className="mt-2 flex items-center gap-2 text-sm font-medium text-accent"><Download className="w-4"/>View sample file / required headings</button></div>
 {!busy&&!analysis&&state!=="completed"&&<label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}} className="flex min-h-52 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-accent/40 bg-card p-8 text-center hover:border-accent"><input className="hidden" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>choose(e.target.files[0])}/><FileSpreadsheet className="mb-3 h-10 w-10 text-accent"/><b>{file?file.name:"Drag & drop your Excel file here"}</b><span className="mt-1 text-sm text-muted-foreground">{file?`${(file.size/1024).toFixed(1)} KB · Ready for analysis`:"or click to browse · .xlsx only · max 15 MB"}</span></label>}
 {busy&&<div className="rounded-xl border bg-card p-8 text-center"><div className="mx-auto mb-5 h-12 w-12 animate-spin rounded-full border-4 border-accent/20 border-t-accent"/><h4 className="font-semibold">{state==="analyzing"?"Analyzing file — no database changes yet":state==="uploading"?"Analysis approved. Starting sync…":"Processing valid rows — please do not close"}</h4><p className="mt-2 text-sm text-muted-foreground">{state==="analyzing"?"Checking headings, PAN, GSTIN, source status and existing CRM records.":"Syncing Groups, GST Locations, Persons, phone numbers and emails."}</p><div className="mx-auto mt-5 h-2 max-w-md overflow-hidden rounded-full bg-accent/15"><div className="h-full w-3/4 animate-pulse bg-accent"/></div></div>}
 {state==="analyzed"&&analysis&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h4 className="font-semibold text-blue-900">Analysis complete — review before proceeding</h4><p className="mt-1 text-sm text-blue-800">No records have been inserted yet. Only {analysis.validRows} valid rows will be synced.</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{[["Total rows",analysis.totalRows],["Valid rows",analysis.validRows],["Invalid rows",analysis.invalidRows],["Groups to create",analysis.groupsToCreate],["Groups to update",analysis.groupsToUpdate],["GSTs to create",analysis.locationsToCreate],["GSTs to update",analysis.locationsToUpdate]].map(([label,value])=><div key={label} className="rounded-lg bg-white p-3"><b className="block text-lg">{value}</b><span className="text-muted-foreground">{label}</span></div>)}</div>{analysis.invalidRows>0&&<div className="mt-4"><button onClick={()=>saveInvalidReport(analysis)} className="flex items-center gap-2 rounded border border-amber-300 bg-white px-3 py-2 text-sm font-medium text-amber-800"><Download className="w-4"/>Download {analysis.invalidRows} invalid rows (.xlsx)</button><div className="mt-3 max-h-28 overflow-auto text-sm text-amber-800">{analysis.issues.map(x=><p key={`${x.row}-${x.message}`}>Row {x.row}: {x.message} {x.pan&&`· PAN ${x.pan}`} {x.gstin&&`· GSTIN ${x.gstin}`}</p>)}</div></div>}</div>}
 {state==="completed"&&result&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-semibold text-emerald-800"><CheckCircle2 className="w-5"/>Buyer directory sync completed</div><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{[["Rows analyzed",result.rows],["Groups created",result.groupsCreated],["GST locations created",result.locationsCreated],["Contacts created",result.contactsCreated],["Groups updated",result.groupsUpdated],["Locations updated",result.locationsUpdated],["Contacts reused",result.contactsReused],["Invalid rows skipped",result.skipped]].map(([label,value])=><div key={label} className="rounded-lg bg-white p-3"><b className="block text-lg">{value}</b><span className="text-muted-foreground">{label}</span></div>)}</div>{analysis?.invalidRows>0&&<button onClick={()=>saveInvalidReport(analysis)} className="mt-4 flex items-center gap-2 rounded border border-amber-300 bg-white px-3 py-2 text-sm font-medium text-amber-800"><Download className="w-4"/>Download invalid rows report</button>}</div>}
 {state==="failed"&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">Import failed. Your database was not partially updated; fix the file and try again.</p>}
 <div className="flex justify-end gap-2"><button disabled={busy} onClick={close} className="h-10 rounded-md border px-4 disabled:opacity-40">{state==="completed"?"Done":"Cancel"}</button>{!analysis&&state!=="completed"&&<button disabled={!file||busy} onClick={analyze} className="h-10 rounded-md bg-accent px-4 font-medium text-accent-foreground disabled:opacity-40">{state==="analyzing"?"Analyzing…":"Analyze File"}</button>}{state==="analyzed"&&<button disabled={!analysis.validRows} onClick={proceed} className="h-10 rounded-md bg-emerald-600 px-4 font-medium text-white disabled:opacity-40">Proceed & Sync {analysis.validRows} Valid Rows</button>}</div>
 </div>}
function Profile({buyer,tab,setTab,close,contactForm,setContactForm,locationForm,setLocationForm,addChild}){const overview=[["Group Name",buyer.group_name],["PAN",buyer.pan],["GST Slab",buyer.gst_slab],["State",buyer.state],["Parent Location",buyer.parent_location],["Lead Manager",buyer.lead_manager],["Reference",buyer.reference],["Group Tag",buyer.group_tag],["Lifecycle",buyer.calculated_lifecycle_status],["Remarks",buyer.remark]];return <Modal title={buyer.group_name} close={close}><div className="mb-5 flex gap-1 overflow-x-auto border-b">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab===t?"border-accent font-medium":"border-transparent text-muted-foreground"}`}>{t}</button>)}</div>
 {tab==="Overview"&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{overview.map(([l,v])=><div key={l} className="rounded-lg bg-card p-3"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-sm font-medium">{show(v)}</p></div>)}</div>}
 {tab==="Custom Fields"&&<BuyerCustomFields buyer={buyer}/>} 
 {tab==="Contacts"&&<Section title="Contacts" action={()=>setContactForm({name:"",is_primary:false})}>{buyer.contacts.map(c=><div key={c.id} className="rounded-lg border p-3 text-sm"><b>{c.name}</b>{c.is_primary&&<span className="ml-2 rounded bg-accent/15 px-2 py-0.5 text-xs">Primary</span>}<p>{show(c.designation)} · {show(c.department)}</p><p>{show(c.mobile_number)} · {show(c.email_address)}</p></div>)}{contactForm&&<MiniForm data={contactForm} setData={setContactForm} fields={[["Name","name"],["Department","department"],["Designation","designation"],["Mobile Number","mobile_number"],["Email","email_address"],["WhatsApp","whatsapp_number"],["Notes","notes"]]} save={()=>addChild("contacts",contactForm)} primary/>}</Section>}
 {tab==="Locations"&&<Section title="Locations" action={()=>setLocationForm({name:""})}>{buyer.locations.map(l=><div key={l.id} className="rounded-lg border p-3 text-sm"><b>{l.name}</b><p>{show(l.address)}, {show(l.city)}, {show(l.state)}</p><p>GST: {show(l.gst_number)} · Business Type: {show(l.business_type)}</p><p>{l.turnover_heading||"Turnover"}: {show(l.turnover)} · Status: {show(l.registration_status)}</p></div>)}{locationForm&&<MiniForm data={locationForm} setData={setLocationForm} fields={[["Location Name","name"],["GST Number","gst_number"],["PAN","pan"],["Address","address"],["City","city"],["State","state"],["Delivery Preferences","delivery_preferences"],["Credit Terms","credit_terms"]]} save={()=>addChild("locations",locationForm)}/>}</Section>}
 {tab==="CRM Information"&&<div className="grid gap-3 sm:grid-cols-3">{[["Lead Type",buyer.lead_type],["Monthly Consumption",buyer.monthly_consumption],["Call Date",buyer.call_date],["Next Call Date",buyer.next_call_date],["Days Since Last Call",buyer.days_since_last_call],["Follow-Up Days",buyer.follow_up_days],["Profile Shared",buyer.profile_shared?"Yes":"No"],["Quote Shared",buyer.quote_shared?"Yes":"No"],["Order Status",buyer.order_status],["Credit Interest",buyer.credit_interest],["Order Count",buyer.order_count],["First Order Date",buyer.first_order_date],["Last Order Date",buyer.last_order_date]].map(([l,v])=><div key={l} className="rounded bg-card p-3"><small>{l}</small><p className="font-medium">{show(v)}</p></div>)}</div>}
 {tab==="Activity Timeline"&&<div className="space-y-3">{buyer.activities.map(a=><div key={a.id} className="border-l-2 border-accent pl-4"><b className="text-sm">{a.description}</b><p className="text-xs text-muted-foreground">{new Date(a.occurred_at).toLocaleString()}</p></div>)}</div>}
 {tab==="Transactions"&&<div><a href={`/orders?buyer=${buyer.id}`} className="mb-4 inline-block rounded bg-accent px-4 py-2 text-sm font-medium">New Inquiry</a>{buyer.transactions?.map(t=><a key={t.id} href={`/orders?transaction=${t.id}`} className="grid grid-cols-5 gap-2 border-b p-3 text-sm hover:bg-card"><b>{t.inquiry_number}</b><span>{t.inquiry_date}</span><span>{t.current_stage}</span><span>₹{t.current_quote}</span><span>{t.status}</span></a>)}</div>}
 {tab==="Finance"&&<PaymentBehaviour buyerId={buyer.id}/>} {tab==="Documents"&&<div className="rounded-lg border border-dashed p-10 text-center text-muted-foreground">Documents are reserved for future integration and will reference this Buyer Group.</div>}
 </Modal>}
function PaymentBehaviour({buyerId}){const[d,setD]=useState(null);useEffect(()=>{api(`/finance/buyers/${buyerId}/payment-behaviour`).then(setD)},[buyerId]);if(!d)return <p className="p-8 text-center text-muted-foreground">Loading payment behaviour…</p>;return <div><h4 className="mb-3 font-semibold">Payment Behaviour</h4><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Total Credit Sales",d.total_credit_sales],["Total Outstanding",d.total_outstanding],["Current Overdue",d.current_overdue_amount],["Average Payment Delay",`${Number(d.average_payment_delay||0).toFixed(1)} days`],["Maximum Payment Delay",`${d.maximum_payment_delay||0} days`],["Overdue Invoices",d.overdue_invoices],["Delayed Payment Charges",d.total_delayed_payment_charges],["Debit Notes Generated",d.total_debit_notes],["Pending Debit Notes",d.pending_debit_notes],["Payment Behaviour Score",`${Number(d.payment_behaviour_score||0).toFixed(1)}/100`]].map(([l,v])=><div key={l} className="rounded bg-card p-3"><small>{l}</small><p className="font-medium">{v}</p></div>)}</div></div>}
function Section({title,action,children}){return <div><div className="mb-3 flex justify-between"><h4 className="font-medium">{title}</h4><button onClick={action} className="flex items-center gap-1 rounded bg-accent px-3 py-1.5 text-sm text-accent-foreground"><Plus className="w-3"/>Add</button></div><div className="space-y-2">{children}</div></div>}
function MiniForm({data,setData,fields,save,primary}){return <div className="grid gap-2 rounded-lg bg-card p-3 sm:grid-cols-2">{fields.map(([l,n])=><Field key={n} label={l} name={n} form={data} setForm={setData}/>) }{primary&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!data.is_primary} onChange={e=>setData({...data,is_primary:e.target.checked})}/>Primary Contact</label>}<div className="sm:col-span-2"><button onClick={save} className="rounded bg-primary px-3 py-2 text-sm text-white">Save</button></div></div>}
function BuyerCustomFields({buyer}){const[fields,setFields]=useState(buyer.custom_fields||[]),toast=useToast();async function save(e){e.preventDefault();const form=new FormData(e.currentTarget),values={};for(const f of fields){const raw=f.field_type==="Checkbox"?form.get(f.field_key)==="on":form.get(f.field_key);values[f.field_key]=["Number","Currency","Percentage"].includes(f.field_type)&&raw!==""?+raw:raw}try{const updated=await api(`/buyers/${buyer.id}`,{method:"PUT",body:JSON.stringify({custom_fields:values})});setFields(updated.custom_fields||[]);toast("Buyer custom fields saved.")}catch(e){toast(e.message,"error")}}if(!fields.length)return <div className="rounded border border-dashed p-8 text-center text-sm text-muted-foreground">No custom fields configured for Buyer Master. Create one from the Configuration Centre.</div>;return <form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{fields.map(f=><label key={f.field_key}><span className="mb-1 block text-xs font-medium">{f.label}</span>{f.field_type==="Checkbox"?<input name={f.field_key} type="checkbox" defaultChecked={!!f.value}/>:<input name={f.field_key} required={f.is_required} type={["Number","Currency","Percentage"].includes(f.field_type)?"number":f.field_type==="Date"?"date":"text"} defaultValue={f.value??""} className="h-10 w-full rounded border px-3"/>}</label>)}<div className="sm:col-span-2"><button className="rounded bg-accent px-4 py-2">Save Custom Fields</button></div></form>}
