import { useEffect, useState } from "react";
import { ChevronDown, Download, Eye, Filter, Plus, Search, Settings2, X } from "lucide-react";
import DashboardLayout from "../components/layout/DashboardLayout";
import { api } from "../lib/api";
import { useToast } from "../components/toast";

const COLUMNS = [
  ["group_name","Group Name"],["primary_contact_number","Primary Contact Number"],["primary_contact_name","Primary Contact Name"],
  ["primary_contact_designation","Primary Contact Designation"],["grades","Grades"],["application","Application"],["pan","PAN"],
  ["gst_slab","GST Slab"],["state","State"],["group_tag","Group Tag"],["reference","Reference"],["sub_application","Sub Application"],
  ["remark","Remark"],["hsn_code","HSN Code"],["lead_manager","Lead Manager"],["parent_location","Parent Location"]
];
const EMPTY={group_name:"",pan:"",primary_contact_name:"",primary_contact_number:"",primary_contact_designation:"",gst_slab:"",state:"",group_tag:"",reference:"",parent_location:"",remark:"",lead_manager:"",lead_type:"",monthly_consumption:"",call_date:"",next_call_date:"",call_remark:"",profile_shared:false,quote_shared:false,order_status:"Prospect",credit_interest:""};
const TABS=["Overview","Contacts","Locations","CRM Information","Activity Timeline","Quotations","Orders","Finance","Documents"];
const show=(v)=>v===null||v===undefined||v===""?"—":String(v);

function Field({label,name,form,setForm,type="text",required=false,wide=false}) { return <label className={wide?"sm:col-span-2":""}><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}</span>{type==="textarea"?<textarea value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})} className="min-h-20 w-full rounded-md border border-input p-2 text-sm"/>:<input required={required} type={type} value={form[name]??""} onChange={e=>setForm({...form,[name]:type==="checkbox"?e.target.checked:e.target.value})} checked={type==="checkbox"?!!form[name]:undefined} className={type==="checkbox"?"h-4 w-4":"h-10 w-full rounded-md border border-input px-3 text-sm"}/>}</label> }

export default function Clients(){
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[sort,setSort]=useState("created_at"),[direction,setDirection]=useState("desc");
 const [visible,setVisible]=useState(()=>COLUMNS.map(c=>c[0])),[columnsOpen,setColumnsOpen]=useState(false),[formOpen,setFormOpen]=useState(false),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false);
 const [selected,setSelected]=useState(null),[tab,setTab]=useState("Overview"),[contactForm,setContactForm]=useState(null),[locationForm,setLocationForm]=useState(null); const toast=useToast();
 async function load(){setLoading(true);try{const q=new URLSearchParams({search,sort,direction,limit:"100"});const result=await api(`/buyers?${q}`);setRows(result.data);setTotal(result.total);}catch(e){toast(e.message,"error");}finally{setLoading(false)}}
 // Reload the server-side result when the active search/sort changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id)},[search,sort,direction]);
 async function openBuyer(id){try{setSelected(await api(`/buyers/${id}`));setTab("Overview")}catch(e){toast(e.message,"error")}}
 async function save(e){e.preventDefault();setSaving(true);try{const payload={...form,monthly_consumption:form.monthly_consumption===""?null:Number(form.monthly_consumption)};const buyer=await api("/buyers",{method:"POST",body:JSON.stringify(payload)});setFormOpen(false);setForm(EMPTY);toast("Buyer Group created.");load();openBuyer(buyer.id)}catch(e){toast(e.message,"error")}finally{setSaving(false)}}
 function sortBy(key){if(sort===key)setDirection(direction==="asc"?"desc":"asc");else{setSort(key);setDirection("asc")}}
 function exportCsv(){const cols=COLUMNS.filter(c=>visible.includes(c[0]));const csv=[cols.map(c=>c[1]),...rows.map(r=>cols.map(c=>r[c[0]]??""))].map(line=>line.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="buyers-filtered.csv";a.click();URL.revokeObjectURL(a.href)}
 async function addChild(kind,data){try{await api(`/buyers/${selected.id}/${kind}`,{method:"POST",body:JSON.stringify(data)});toast(`${kind==="contacts"?"Contact":"Location"} added.`);setSelected(await api(`/buyers/${selected.id}`));setContactForm(null);setLocationForm(null)}catch(e){toast(e.message,"error")}}
 return <DashboardLayout title="Buyers"><div className="space-y-4">
  <section className="flex flex-col gap-3 rounded-xl border border-border bg-white p-5 shadow-card lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold">Buyer Groups</h2><p className="text-sm text-muted-foreground">One Buyer Group per PAN · {total} records</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="flex h-9 items-center gap-2 rounded-md border px-3 text-sm"><Download className="w-4"/>Export filtered</button><button onClick={()=>setFormOpen(true)} className="flex h-9 items-center gap-2 rounded-md bg-accent px-3 text-sm font-medium text-accent-foreground"><Plus className="w-4"/>Add Buyer Group</button></div></section>
  <section className="overflow-hidden rounded-xl border border-border bg-white shadow-card"><div className="flex flex-wrap items-center gap-2 border-b p-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 w-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search group, PAN, contact, state, tag…" className="h-9 w-full rounded-md border pl-9 pr-3 text-sm"/></div><button className="flex h-9 items-center gap-2 rounded-md border px-3 text-sm"><Filter className="w-4"/>Filters</button><div className="relative"><button onClick={()=>setColumnsOpen(!columnsOpen)} className="flex h-9 items-center gap-2 rounded-md border px-3 text-sm"><Settings2 className="w-4"/>Columns<ChevronDown className="w-3"/></button>{columnsOpen&&<div className="absolute right-0 z-20 mt-1 max-h-80 w-64 overflow-auto rounded-lg border bg-white p-2 shadow-lg">{COLUMNS.map(([key,label])=><label key={key} className="flex gap-2 p-2 text-sm"><input type="checkbox" checked={visible.includes(key)} onChange={()=>setVisible(visible.includes(key)?visible.filter(x=>x!==key):[...visible,key])}/>{label}</label>)}</div>}</div></div>
   <div className="max-h-[65vh] overflow-auto"><table className="min-w-max text-left text-sm"><thead className="sticky top-0 z-10 bg-card text-xs uppercase text-muted-foreground"><tr>{COLUMNS.filter(c=>visible.includes(c[0])).map(([key,label])=><th key={key} onClick={()=>sortBy(key)} className={`${key==="group_name"?"sticky left-0 z-20 bg-card":""} cursor-pointer whitespace-nowrap border-r px-4 py-3`}>{label}{sort===key?(direction==="asc"?" ↑":" ↓"):""}</th>)}<th className="px-4">View</th></tr></thead><tbody>{loading?<tr><td className="p-10 text-center" colSpan={visible.length+1}>Loading…</td></tr>:rows.map(r=><tr key={r.id} className="border-t hover:bg-card/60">{COLUMNS.filter(c=>visible.includes(c[0])).map(([key])=><td key={key} className={`${key==="group_name"?"sticky left-0 bg-white font-medium":""} max-w-64 truncate whitespace-nowrap border-r px-4 py-3`}>{show(r[key])}</td>)}<td className="px-4"><button onClick={()=>openBuyer(r.id)} className="rounded p-2 text-primary hover:bg-card"><Eye className="w-4"/></button></td></tr>)}</tbody></table></div>
  </section>
 </div>
 {formOpen&&<Modal title="Add Buyer Group" close={()=>setFormOpen(false)}><form onSubmit={save}><BuyerFields form={form} setForm={setForm}/><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setFormOpen(false)} className="h-10 rounded-md border px-4">Cancel</button><button disabled={saving} className="h-10 rounded-md bg-accent px-4 font-medium text-accent-foreground">{saving?"Saving…":"Save Buyer"}</button></div></form></Modal>}
 {selected&&<Profile buyer={selected} tab={tab} setTab={setTab} close={()=>setSelected(null)} contactForm={contactForm} setContactForm={setContactForm} locationForm={locationForm} setLocationForm={setLocationForm} addChild={addChild}/>} </DashboardLayout>
}

function BuyerFields({form,setForm}){return <div className="grid gap-4 sm:grid-cols-2"><Field label="Group Name" name="group_name" required form={form} setForm={setForm}/><Field label="PAN (one Group = one PAN)" name="pan" required form={form} setForm={setForm}/><Field label="Primary Contact Name" name="primary_contact_name" form={form} setForm={setForm}/><Field label="Primary Contact Number" name="primary_contact_number" form={form} setForm={setForm}/><Field label="Primary Contact Designation" name="primary_contact_designation" form={form} setForm={setForm}/>{[["GST Slab","gst_slab"],["State","state"],["Group Tag","group_tag"],["Reference","reference"],["Lead Manager","lead_manager"],["Parent Location","parent_location"],["Lead Type","lead_type"],["Monthly Consumption","monthly_consumption"],["Call Date","call_date","date"],["Next Call Date","next_call_date","date"],["Order Status","order_status"],["Credit Interest","credit_interest"]].map(([l,n,t])=><Field key={n} label={l} name={n} type={t} form={form} setForm={setForm}/>)}<Field label="Remark" name="remark" type="textarea" wide form={form} setForm={setForm}/><Field label="Call Remark" name="call_remark" type="textarea" wide form={form} setForm={setForm}/></div>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 grid place-items-center bg-primary/40 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h3 className="text-lg font-semibold">{title}</h3><button onClick={close}><X className="w-5"/></button></div>{children}</div></div>}
function Profile({buyer,tab,setTab,close,contactForm,setContactForm,locationForm,setLocationForm,addChild}){const overview=[["Group Name",buyer.group_name],["PAN",buyer.pan],["GST Slab",buyer.gst_slab],["State",buyer.state],["Parent Location",buyer.parent_location],["Lead Manager",buyer.lead_manager],["Reference",buyer.reference],["Group Tag",buyer.group_tag],["Lifecycle",buyer.calculated_lifecycle_status],["Remarks",buyer.remark]];return <Modal title={buyer.group_name} close={close}><div className="mb-5 flex gap-1 overflow-x-auto border-b">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab===t?"border-accent font-medium":"border-transparent text-muted-foreground"}`}>{t}</button>)}</div>
 {tab==="Overview"&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{overview.map(([l,v])=><div key={l} className="rounded-lg bg-card p-3"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-sm font-medium">{show(v)}</p></div>)}</div>}
 {tab==="Contacts"&&<Section title="Contacts" action={()=>setContactForm({name:"",is_primary:false})}>{buyer.contacts.map(c=><div key={c.id} className="rounded-lg border p-3 text-sm"><b>{c.name}</b>{c.is_primary&&<span className="ml-2 rounded bg-accent/15 px-2 py-0.5 text-xs">Primary</span>}<p>{show(c.designation)} · {show(c.department)}</p><p>{show(c.mobile_number)} · {show(c.email_address)}</p></div>)}{contactForm&&<MiniForm data={contactForm} setData={setContactForm} fields={[["Name","name"],["Department","department"],["Designation","designation"],["Mobile Number","mobile_number"],["Email","email_address"],["WhatsApp","whatsapp_number"],["Notes","notes"]]} save={()=>addChild("contacts",contactForm)} primary/>}</Section>}
 {tab==="Locations"&&<Section title="Locations" action={()=>setLocationForm({name:""})}>{buyer.locations.map(l=><div key={l.id} className="rounded-lg border p-3 text-sm"><b>{l.name}</b><p>{show(l.address)}, {show(l.city)}, {show(l.state)}</p><p>GST: {show(l.gst_number)} · Credit: {show(l.credit_terms)}</p></div>)}{locationForm&&<MiniForm data={locationForm} setData={setLocationForm} fields={[["Location Name","name"],["GST Number","gst_number"],["PAN","pan"],["Address","address"],["City","city"],["State","state"],["Delivery Preferences","delivery_preferences"],["Credit Terms","credit_terms"]]} save={()=>addChild("locations",locationForm)}/>}</Section>}
 {tab==="CRM Information"&&<div className="grid gap-3 sm:grid-cols-3">{[["Lead Type",buyer.lead_type],["Monthly Consumption",buyer.monthly_consumption],["Call Date",buyer.call_date],["Next Call Date",buyer.next_call_date],["Days Since Last Call",buyer.days_since_last_call],["Follow-Up Days",buyer.follow_up_days],["Profile Shared",buyer.profile_shared?"Yes":"No"],["Quote Shared",buyer.quote_shared?"Yes":"No"],["Order Status",buyer.order_status],["Credit Interest",buyer.credit_interest],["Order Count",buyer.order_count],["First Order Date",buyer.first_order_date],["Last Order Date",buyer.last_order_date]].map(([l,v])=><div key={l} className="rounded bg-card p-3"><small>{l}</small><p className="font-medium">{show(v)}</p></div>)}</div>}
 {tab==="Activity Timeline"&&<div className="space-y-3">{buyer.activities.map(a=><div key={a.id} className="border-l-2 border-accent pl-4"><b className="text-sm">{a.description}</b><p className="text-xs text-muted-foreground">{new Date(a.occurred_at).toLocaleString()}</p></div>)}</div>}
 {["Quotations","Orders","Finance","Documents"].includes(tab)&&<div className="rounded-lg border border-dashed p-10 text-center text-muted-foreground">{tab} is reserved for future integration and will reference this Buyer Group.</div>}
 </Modal>}
function Section({title,action,children}){return <div><div className="mb-3 flex justify-between"><h4 className="font-medium">{title}</h4><button onClick={action} className="flex items-center gap-1 rounded bg-accent px-3 py-1.5 text-sm text-accent-foreground"><Plus className="w-3"/>Add</button></div><div className="space-y-2">{children}</div></div>}
function MiniForm({data,setData,fields,save,primary}){return <div className="grid gap-2 rounded-lg bg-card p-3 sm:grid-cols-2">{fields.map(([l,n])=><Field key={n} label={l} name={n} form={data} setForm={setData}/>) }{primary&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!data.is_primary} onChange={e=>setData({...data,is_primary:e.target.checked})}/>Primary Contact</label>}<div className="sm:col-span-2"><button onClick={save} className="rounded bg-primary px-3 py-2 text-sm text-white">Save</button></div></div>}
