import { useEffect, useState } from "react";
import { AlertCircle, ArrowRight, ArrowUpRight, Building2, Clock3, IndianRupee, ListTodo, LoaderCircle, PackageCheck, PhoneCall, Tag, Truck, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "../components/layout/DashboardLayout";
import { api } from "../lib/api";
import { useToast } from "../components/toast";
import { formatDecimal, formatMoney } from "../lib/format";

const money = value => formatMoney(value);
const show = value => value === null || value === undefined ? "—" : formatDecimal(value);
export default function Dashboard() {
  const [data, setData] = useState(null);
  const navigate = useNavigate();
  const toast = useToast();
  useEffect(() => { api("/reports/dashboard").then(setData).catch(error => toast(error.message, "error")); }, [toast]);
  const cards = [
    { label: "Buyers", value: data?.totalBuyers, sub: `${data?.customers || 0} customers`, icon: Users, to: "/buyers" },
    { label: "Active Suppliers", value: data?.totalSuppliers, sub: `${data?.pricesExpiring || 0} prices expiring`, icon: Building2, to: "/suppliers" },
    { label: "Active Orders", value: data?.activeOrders, sub: `${data?.totalOrders || 0} total orders`, icon: PackageCheck, to: "/orders" },
    { label: "Logistics Shipments", value: data?.logisticsShipments, sub: `${data?.deliveriesDue || 0} deliveries due`, icon: Truck, to: "/logistics" },
    { label: "Order Value", value: money(data?.orderValue), sub: "Current order book", icon: IndianRupee, to: "/orders" },
    { label: "Finance Outstanding", value: money(data?.financeOutstanding), sub: `${data?.overduePayments || 0} overdue`, icon: IndianRupee, to: "/finance" }
  ];
  return <DashboardLayout title="Dashboard"><div className="space-y-6">
    <div><h2 className="text-xl font-semibold">Business Overview</h2><p className="text-sm text-muted-foreground">Live view across Buyer, Supplier, Orders, Logistics and Finance.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, value, sub, icon: Icon, to }) => <button key={label} onClick={() => navigate(to)} className="rounded-xl border bg-white p-5 text-left shadow-[0_5px_18px_rgba(15,23,42,0.07)] transition-colors hover:border-accent"><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center rounded bg-primary/10"><Icon className="w-5 text-primary" /></span><ArrowUpRight className="w-4 text-muted-foreground" /></div><p className="mt-3 text-2xl font-bold">{data ? show(value) : "…"}</p><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{sub}</p></button>)}</div>
    <section><div className="mb-4 flex items-center gap-3 rounded-xl border border-violet-100 bg-violet-50 px-4 py-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-violet-100"><ListTodo className="h-5 w-5 text-violet-700"/></span><div><h2 className="text-xl font-semibold text-slate-900">Sales To-do List</h2><p className="text-sm text-slate-600">Today’s prospects and pending buyer follow-ups.</p></div></div><div className="grid gap-4 xl:grid-cols-2"><TodoTable title="Prospect buyers who can order today" rows={data?.prospectsToday} loading={!data} navigate={navigate} kind="prospect"/><TodoTable title="Pending calls and follow-ups" rows={data?.followUpsToday} loading={!data} navigate={navigate} kind="follow-up"/></div></section>
    <div className="grid gap-4 xl:grid-cols-3"><section className="overflow-hidden rounded-xl border bg-white xl:col-span-2"><div className="flex justify-between border-b p-4"><h3 className="font-semibold">Recent Orders</h3><button onClick={() => navigate("/orders")} className="text-sm text-secondary">View all</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["Order", "Buyer", "Product / Grade", "Quantity", "Date", "Status"].map(label => <th key={label} className="border-b p-3 text-left text-xs text-muted-foreground">{label}</th>)}</tr></thead><tbody>{data?.recentOrders?.length ? data.recentOrders.map(order => <tr key={order.id} className="border-b"><td className="p-3 font-medium">{order.order_number}</td><td className="p-3">{order.buyer_name}</td><td className="p-3">{order.product_category} / {order.grade}</td><td className="p-3">{order.quantity_kg} Kg</td><td className="p-3">{order.order_date}</td><td className="p-3">{order.status}</td></tr>) : <tr><td colSpan="6" className="p-10 text-center text-muted-foreground">No orders created yet.</td></tr>}</tbody></table></div></section>
      <AttentionCard data={data} navigate={navigate}/></div>
  </div></DashboardLayout>;
}
function AttentionCard({data,navigate}){const items=[{label:"Overdue payments",count:data?.overduePayments,to:"/finance",icon:AlertCircle,tone:"bg-red-50 text-red-700"},{label:"Deliveries due this week",count:data?.deliveriesDue,to:"/orders",icon:Clock3,tone:"bg-amber-50 text-amber-700"},{label:"Supplier prices expiring",count:data?.pricesExpiring,to:"/suppliers",icon:Tag,tone:"bg-blue-50 text-blue-700"}];return <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-amber-50"><AlertCircle className="h-4 w-4 text-amber-700"/></span><div><h3 className="font-semibold">Attention Required</h3><p className="text-xs text-muted-foreground">Items that may need action.</p></div></div></div><div className="divide-y px-4">{items.map(({label,count,to,icon:Icon,tone})=><button key={label} onClick={()=>navigate(to)} className="group flex w-full items-center gap-3 py-4 text-left"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${tone}`}><Icon className="h-4 w-4"/></span><span className="min-w-0 flex-1 text-sm font-medium">{label}</span><span className="text-lg font-semibold tabular-nums">{count??"…"}</span><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-0.5"/></button>)}</div><div className="border-t bg-card/50 p-3"><button onClick={()=>navigate("/reports")} className="w-full rounded-lg border bg-white px-3 py-2 text-sm font-medium text-secondary transition hover:border-secondary/40 hover:bg-card">Open Reports</button></div></section>}
function TodoTable({title,rows,loading,navigate,kind}){const prospect=kind==="prospect",headings=prospect?["Buyer","Contact","Consumption","Next call","Latest remark","Owner",""]:["Buyer","Contact","Last call","Due date","Latest remark","Owner",""];return <section className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center justify-between border-b p-4"><div className="flex items-center gap-2">{prospect?<Users className="h-4 w-4 text-accent"/>:<PhoneCall className="h-4 w-4 text-accent"/>}<h3 className="font-semibold">{title}</h3></div>{!loading&&<span className="rounded-full bg-accent/10 px-2.5 py-1 text-xs font-medium text-accent">{rows?.length||0}</span>}</div><div className="max-h-80 overflow-auto"><table className="min-w-[780px] w-full text-sm"><thead className="sticky top-0 bg-card"><tr>{headings.map((x,index)=><th key={`${x}-${index}`} className="border-b p-3 text-left text-xs text-muted-foreground">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="7" className="p-10 text-center text-muted-foreground"><LoaderCircle className="mx-auto mb-2 h-6 w-6 animate-spin text-accent"/>Loading sales to-dos…</td></tr>:rows?.length?rows.map(row=><tr key={row.id} className="border-b hover:bg-card"><td className="p-3 font-medium text-secondary">{row.group_name}</td><td className="p-3"><p>{row.primary_contact_name||"—"}</p><p className="text-xs text-muted-foreground">{row.primary_contact_number||"—"}</p></td>{prospect?<><td className="p-3">{show(row.monthly_consumption)}</td><td className="p-3">{row.next_call_date||"Not scheduled"}</td></>:<><td className="p-3">{row.call_date||"—"}</td><td className="p-3"><span className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-800">{row.next_call_date}</span></td></>}<td className="max-w-52 truncate p-3" title={row.call_remark||""}>{row.call_remark||"No call remark"}</td><td className="p-3">{row.lead_manager||"Unassigned"}</td><td className="p-3"><button onClick={()=>navigate(`/buyers?buyer=${row.id}&tab=follow-up`)} className="whitespace-nowrap rounded border px-2.5 py-1.5 text-xs font-medium text-secondary hover:bg-card">Open follow-up</button></td></tr>):<tr><td colSpan="7" className="p-8 text-center text-muted-foreground">{prospect?"No prospective buyers require action today.":"No pending calls or follow-ups."}</td></tr>}</tbody></table></div></section>}
