import { useEffect,useState } from "react";
import { ArrowLeft,CheckCircle2,Download,FileSpreadsheet,Upload,XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import DashboardLayout from "../components/layout/DashboardLayout";
import { api,download } from "../lib/api";
import { useToast } from "../components/toast";
import { formatMoney } from "../lib/format";

const busyStates=new Set(["analyzing","importing"]);
export default function FreightBulkUpload(){
 const[file,setFile]=useState(null),[state,setState]=useState("idle"),[analysis,setAnalysis]=useState(null),[result,setResult]=useState(null),[history,setHistory]=useState([]),[rates,setRates]=useState([]),toast=useToast();
 async function loadHistory(){try{const[imports,baseRates]=await Promise.all([api("/logistics/freight-import/history"),api("/logistics/base-freight")]);setHistory(Array.isArray(imports)?imports:[]);setRates(Array.isArray(baseRates)?baseRates:[])}catch(e){setHistory([]);setRates([]);toast(e.message,"error")}}
 useEffect(()=>{void loadHistory()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 function choose(next){if(!next)return;if(!/\.(csv|xlsx)$/i.test(next.name)){toast("Select a CSV or XLSX freight file.","error");return}if(next.size>15*1024*1024){toast("Freight file must not exceed 15 MB.","error");return}setFile(next);setAnalysis(null);setResult(null);setState("ready")}
 async function analyze(){const body=new FormData();body.append("file",file);setState("analyzing");try{setAnalysis(await api("/logistics/freight-import/analyze",{method:"POST",body}));setState("analyzed")}catch(e){setState("failed");toast(e.message,"error")}}
 async function importRows(){const body=new FormData();body.append("file",file);setState("importing");try{const x=await api("/logistics/freight-import",{method:"POST",body});setResult(x);setState("complete");loadHistory();toast("Base freight rates imported.")}catch(e){setState("failed");toast(e.message,"error")}}
 function invalidRows(){if(!analysis?.invalidReport)return;const bytes=Uint8Array.from(atob(analysis.invalidReport),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a");a.href=url;a.download="invalid-freight-rows.xlsx";a.click();URL.revokeObjectURL(url)}
 function reset(){setFile(null);setAnalysis(null);setResult(null);setState("idle")}
 return <DashboardLayout title="Freight Bulk Upload"><div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/logistics" className="mb-2 inline-flex items-center gap-1 text-sm text-secondary"><ArrowLeft className="w-4"/>Back to Logistics</Link><h2 className="text-xl font-semibold">Base Freight Bulk Upload</h2><p className="text-sm text-muted-foreground">Client format: FROM, TO, LOAD in KG, FREIGHT in Rs/Kg.</p></div><button onClick={()=>download("/logistics/freight-import/template","freight-base-rate-template.xlsx")} className="inline-flex items-center gap-2 rounded border px-4 py-2 text-sm"><Download className="w-4"/>Download template</button></div>
  <section className="rounded-xl border bg-white p-5">{state==="idle"||state==="ready"?<label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files?.[0])}} className="flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-accent/40 bg-card p-8 text-center"><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={e=>choose(e.target.files?.[0])}/><FileSpreadsheet className="mb-3 h-11 w-11 text-accent"/><b>{file?.name||"Drop the client freight file here"}</b><span className="mt-1 text-sm text-muted-foreground">CSV or XLSX · maximum 15 MB</span></label>:null}
   {busyStates.has(state)&&<div className="p-12 text-center"><div className="mx-auto mb-4 h-11 w-11 animate-spin rounded-full border-4 border-accent/20 border-t-accent"/><b>{state==="analyzing"?"Analyzing rows and duplicates…":"Importing versioned freight rates…"}</b><p className="mt-2 text-sm text-muted-foreground">Do not close this page.</p></div>}
   {analysis&&state==="analyzed"&&<div><h3 className="font-semibold">Analysis complete — no database changes yet</h3><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[["Total",analysis.totalRows],["Valid",analysis.validRows],["Invalid",analysis.invalidRows],["New",analysis.newRows],["Updates",analysis.updates]].map(([l,v])=><div key={l} className="rounded bg-card p-3"><b className="block text-xl">{v}</b><small>{l}</small></div>)}</div>{analysis.issues?.length>0&&<div className="mt-4 rounded border border-red-200 bg-red-50 p-4"><div className="flex justify-between"><b className="text-red-700">Invalid rows must be corrected</b><button onClick={invalidRows} className="text-sm font-medium text-red-700"><Download className="mr-1 inline w-4"/>Error Excel</button></div>{analysis.issues.slice(0,20).map(x=><p key={x.row} className="mt-1 text-sm">Row {x.row}: {x.error}</p>)}</div>}</div>}
   {result&&state==="complete"&&<div className="p-8 text-center"><CheckCircle2 className="mx-auto mb-3 h-12 w-12 text-green-600"/><h3 className="text-lg font-semibold">Import completed</h3><p className="mt-2">{result.inserted} new · {result.updated} updated · {result.unchanged} unchanged</p></div>}
   {state==="failed"&&<div className="p-8 text-center text-red-700"><XCircle className="mx-auto mb-2 h-10 w-10"/>Upload failed. Correct the file and analyze again.</div>}
   <div className="mt-5 flex justify-end gap-2">{state!=="idle"&&!busyStates.has(state)&&<button onClick={reset} className="rounded border px-4 py-2">Choose another file</button>}{state==="ready"&&<button onClick={analyze} className="rounded bg-accent px-4 py-2 font-medium"><Upload className="mr-1 inline w-4"/>Analyze File</button>}{state==="analyzed"&&<button disabled={!analysis.validRows||analysis.invalidRows>0} onClick={importRows} className="rounded bg-emerald-600 px-4 py-2 font-medium text-white disabled:opacity-40">Proceed & Import {analysis.validRows} Rows</button>}</div>
  </section>
  <section className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-semibold">Active Base Freight Rates</h3><p className="text-xs text-muted-foreground">Imported records used by the Freight Engine · Freight unit Rs/Kg</p></div><b className="rounded bg-card px-3 py-1 text-sm">{rates.length} rates</b></div><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-card"><tr>{["From","To","Load (KG)","Freight (Rs/Kg)","Version","Source","Effective From"].map(x=><th key={x} className="border-b p-3 text-left">{x}</th>)}</tr></thead><tbody>{rates.map(x=><tr key={x.id} className="border-b"><td className="p-3 font-medium">{x.from_district}</td><td className="p-3 font-medium">{x.to_district}</td><td className="p-3">{Number(x.quantity_kg).toLocaleString("en-IN")}</td><td className="p-3">{formatMoney(x.base_freight_per_kg)}</td><td className="p-3">v{x.version}</td><td className="p-3">{x.source}</td><td className="p-3">{x.effective_from}</td></tr>)}</tbody></table>{!rates.length&&<p className="p-8 text-center text-muted-foreground">No active base freight rates imported yet.</p>}</div></section>
  <section className="overflow-hidden rounded-xl border bg-white"><h3 className="border-b p-4 font-semibold">Import History</h3><div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{["Date","File","Status","Rows","New","Updated","User"].map(x=><th key={x} className="border-b p-3 text-left">{x}</th>)}</tr></thead><tbody>{history.map(x=><tr key={x.id} className="border-b"><td className="p-3">{new Date(x.created_at).toLocaleString()}</td><td className="p-3">{x.filename}</td><td className="p-3">{x.status}</td><td className="p-3">{x.total_rows}</td><td className="p-3">{x.inserted_rows}</td><td className="p-3">{x.updated_rows}</td><td className="p-3">{x.uploaded_by_name||"—"}</td></tr>)}</tbody></table>{!history.length&&<p className="p-8 text-center text-muted-foreground">No freight imports yet.</p>}</div></section>
 </div></DashboardLayout>
}
