import { useCallback, useEffect, useState } from "react";
import { FileText, Pencil, Plus, Search, Trash2, Upload, X } from "lucide-react";
import DashboardLayout from "../components/layout/DashboardLayout";
import { api } from "../lib/api";
import { can } from "../lib/permissions";
import { useToast } from "../components/toast";

const blank={company:"",country:"",method:"Rutile",grade:"",application:"Paints",description:"",category:"Titanium Dioxide (TiO2)",is_active:true,sort_order:0};
const methods=["Rutile","Anatase"],applications=["Paints","Coating","Plastics/PVC","Masterbatch","Inks","General"];

export default function WebsiteProducts(){
  const[response,setResponse]=useState({rows:[],total:0,page:1,pages:1}),[filters,setFilters]=useState({search:"",company:"",country:"",method:"",application:"",is_active:"",page:1,limit:25}),[form,setForm]=useState(null),[uploading,setUploading]=useState(null),[loading,setLoading]=useState(true);const toast=useToast();
  const canCreate=can("create"),canUpdate=can("update"),canDelete=can("delete");
  const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==""&&v!==undefined));setResponse(await api(`/products?${q}`))}catch(e){toast(e.message,"error")}finally{setLoading(false)}},[filters,toast]);
  useEffect(()=>{const timer=setTimeout(load,filters.search?250:0);return()=>clearTimeout(timer)},[filters.search,load]);
  const setFilter=(name,value)=>setFilters(current=>({...current,[name]:value,page:1}));
  async function remove(product){if(!confirm(`Delete ${product.grade} (${product.application})? This cannot be undone.`))return;try{await api(`/products/${product.id}`,{method:"DELETE"});toast("Website product deleted.");load()}catch(e){toast(e.message,"error")}}
  async function toggle(product){try{await api(`/products/${product.id}`,{method:"PUT",body:JSON.stringify({is_active:!product.is_active})});toast(`Product ${product.is_active?"deactivated":"activated"}.`);load()}catch(e){toast(e.message,"error")}}
  async function uploadPdf(product,file){if(!file)return;const body=new FormData();body.append("datasheet",file);setUploading(product.id);try{await api(`/products/${product.id}/datasheet`,{method:"POST",body});toast("Datasheet uploaded.");load()}catch(e){toast(e.message,"error")}finally{setUploading(null)}}
  const options=(key)=>[...new Set(response.rows.map(row=>row[key]).filter(Boolean))].sort();
  return <DashboardLayout title="Website Products"><div className="space-y-4">
    <section className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5"><div><h2 className="text-lg font-semibold">Website Product Catalogue</h2><p className="text-sm text-muted-foreground">Manage the products and PDF datasheets published on the Cresco website · {response.total} records</p></div>{canCreate&&<button onClick={()=>setForm({...blank})} className="flex h-9 items-center gap-2 rounded bg-accent px-4 text-sm font-medium"><Plus className="w-4"/>Add Product</button>}</section>
    <section className="rounded-xl border bg-white"><div className="grid gap-3 border-b p-4 md:grid-cols-3 xl:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 w-4 text-muted-foreground"/><input value={filters.search} onChange={e=>setFilter("search",e.target.value)} placeholder="Search company, grade, application…" className="h-9 w-full rounded border pl-9 pr-3 text-sm"/></label><Filter label="All companies" value={filters.company} set={v=>setFilter("company",v)} rows={options("company")}/><Filter label="All methods" value={filters.method} set={v=>setFilter("method",v)} rows={methods}/><Filter label="All applications" value={filters.application} set={v=>setFilter("application",v)} rows={applications}/><Filter label="All statuses" value={filters.is_active} set={v=>setFilter("is_active",v)} rows={[{value:"true",label:"Active"},{value:"false",label:"Inactive"}]}/></div>
      <div className="max-h-[64vh] overflow-auto"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-card"><tr>{["Image","Company","Grade","Method","Application","Country","Status","Datasheet","Actions"].map(x=><th key={x} className="whitespace-nowrap border-b p-3 text-left">{x}</th>)}</tr></thead><tbody>{response.rows.map(product=><tr key={product.id} className="border-b hover:bg-card/40"><td className="p-3">{product.image_url?<img src={product.image_url} alt="" className="h-10 w-10 rounded border object-cover"/>:<span className="text-muted-foreground">—</span>}</td><td className="p-3">{product.company}</td><td className="p-3 font-medium">{product.grade}</td><td className="p-3">{product.method}</td><td className="p-3">{product.application}</td><td className="p-3">{product.country||"—"}</td><td className="p-3"><button disabled={!canUpdate} onClick={()=>toggle(product)} className={`rounded-full px-2.5 py-1 text-xs ${product.is_active?"bg-green-100 text-green-700":"bg-gray-100 text-gray-600"}`}>{product.is_active?"Active":"Inactive"}</button></td><td className="p-3">{product.datasheet_url?<a href={product.datasheet_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-accent hover:underline"><FileText className="w-4"/>Open</a>:<span className="text-muted-foreground">Missing</span>}</td><td className="p-3"><div className="flex items-center gap-2">{canUpdate&&<><button title="Edit" onClick={()=>setForm({...product})} className="rounded border p-2"><Pencil className="w-4"/></button><label title="Upload or replace PDF" className={`cursor-pointer rounded border p-2 ${uploading===product.id?"opacity-50":""}`}><Upload className="w-4"/><input disabled={uploading===product.id} type="file" accept="application/pdf,.pdf" className="hidden" onChange={e=>uploadPdf(product,e.target.files?.[0])}/></label></>}{canDelete&&<button title="Delete" onClick={()=>remove(product)} className="rounded border p-2 text-error"><Trash2 className="w-4"/></button>}</div></td></tr>)}</tbody></table>{!loading&&!response.rows.length&&<p className="p-12 text-center text-sm text-muted-foreground">No website products match these filters.</p>}{loading&&<p className="p-12 text-center text-sm text-muted-foreground">Loading website products…</p>}</div>
      <div className="flex items-center justify-between border-t p-4 text-sm"><span>Page {response.page} of {response.pages}</span><div className="flex gap-2"><button disabled={response.page<=1} onClick={()=>setFilters(x=>({...x,page:x.page-1}))} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={response.page>=response.pages} onClick={()=>setFilters(x=>({...x,page:x.page+1}))} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div></div>
    </section>
  </div>{form&&<ProductModal product={form} close={()=>setForm(null)} saved={()=>{setForm(null);load()}} toast={toast}/>}</DashboardLayout>
}

function Filter({label,value,set,rows}){return <select value={value} onChange={e=>set(e.target.value)} className="h-9 rounded border bg-white px-2 text-sm"><option value="">{label}</option>{rows.map(row=>typeof row==="string"?<option key={row}>{row}</option>:<option key={row.value} value={row.value}>{row.label}</option>)}</select>}
function Field({label,name,value,type="text",required,onChange,wide=false,options}){return <label className={wide?"sm:col-span-2":""}><span className="mb-1 block text-xs font-medium">{label}</span>{type==="textarea"?<textarea value={value??""} onChange={e=>onChange(name,e.target.value)} required={required} className="min-h-24 w-full rounded border p-2"/>:options?<select value={value??""} onChange={e=>onChange(name,e.target.value)} required={required} className="h-10 w-full rounded border bg-white px-3">{options.map(x=><option key={x}>{x}</option>)}</select>:<input value={value??""} onChange={e=>onChange(name,type==="number"?Number(e.target.value):e.target.value)} required={required} type={type} className="h-10 w-full rounded border px-3"/>}</label>}
function ProductModal({product,close,saved,toast}){const[data,setData]=useState(product),[image,setImage]=useState(null),editing=Boolean(product.id);const change=(name,value)=>setData(x=>({...x,[name]:value}));function chooseImage(file){if(!file)return;if(file.size>10*1024*1024){toast("Product image must not exceed 10 MB.","error");return}setImage(file)}async function submit(e){e.preventDefault();try{const savedProduct=await api(editing?`/products/${product.id}`:"/products",{method:editing?"PUT":"POST",body:JSON.stringify(data)});if(image){const body=new FormData();body.append("image",image);await api(`/products/${savedProduct.id}/image`,{method:"POST",body})}toast(`Website product ${editing?"updated":"created"}.`);saved()}catch(e){toast(e.message,"error")}}return <div className="fixed inset-0 z-50 grid place-items-center bg-primary/40 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-6"><div className="mb-5 flex justify-between"><h3 className="text-lg font-semibold">{editing?"Edit":"Add"} Website Product</h3><button onClick={close}><X className="w-5"/></button></div><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Company" name="company" value={data.company} onChange={change} required/><Field label="Country" name="country" value={data.country} onChange={change}/><Field label="Method" name="method" value={data.method} onChange={change} options={methods} required/><Field label="Grade" name="grade" value={data.grade} onChange={change} required/><Field label="Application" name="application" value={data.application} onChange={change} options={applications} required/><Field label="Category" name="category" value={data.category} onChange={change} required/><Field label="Sort Order" name="sort_order" value={data.sort_order} onChange={change} type="number"/><label><span className="mb-1 block text-xs font-medium">Product Image</span><input type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" onChange={e=>chooseImage(e.target.files?.[0])} className="block w-full rounded border p-2 text-sm"/><span className="mt-1 block text-xs text-muted-foreground">JPEG, PNG or WebP · maximum 10 MB</span>{image&&<span className="mt-1 block truncate text-xs text-accent">Selected: {image.name}</span>}{!image&&data.image_url&&<img src={data.image_url} alt="Current product" className="mt-2 h-20 w-20 rounded border object-cover"/>}</label><Field label="Description" name="description" value={data.description} onChange={change} type="textarea" wide required/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.is_active===true} onChange={e=>change("is_active",e.target.checked)}/>Active on public website</label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={close} className="rounded border px-4 py-2">Cancel</button><button className="rounded bg-accent px-5 py-2 font-medium">Save Product</button></div></form></div></div>}
