import { useEffect,useState } from "react";
import { Plus,Search,Upload } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";
import { useToast } from "./toast";

export default function BaseFreightMatrix(){
 const[rows,setRows]=useState([]),[search,setSearch]=useState(""),[form,setForm]=useState({from:"",to:"",load:"",freight:"",remarks:""}),[open,setOpen]=useState(false),toast=useToast();
 async function load(){try{setRows(await api("/logistics/base-freight"))}catch(e){toast(e.message,"error")}}
 useEffect(()=>{load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function save(e){e.preventDefault();try{await api("/logistics/base-freight",{method:"POST",body:JSON.stringify(form)});setForm({from:"",to:"",load:"",freight:"",remarks:""});setOpen(false);await load();toast("Freight rate saved.")}catch(e){toast(e.message,"error")}}
 const filtered=rows.filter(r=>`${r.from_district} ${r.to_district} ${r.quantity_kg}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="unified-freight rounded-lg border"><div className="flex flex-wrap items-center justify-between gap-2 border-b p-4"><div><h3 className="font-semibold">Freight Rates</h3><p className="text-xs text-muted-foreground">Add one rate manually or upload many rates from Excel · Rs/Kg</p></div><div className="flex gap-2"><button onClick={()=>setOpen(!open)} className="rounded bg-accent px-3 py-2 text-sm"><Plus className="mr-1 inline w-4"/>Add Rate</button><Link to="/logistics/freight-upload" className="rounded border px-3 py-2 text-sm"><Upload className="mr-1 inline w-4"/>Upload Excel</Link></div></div>
 {open&&<form onSubmit={save} className="grid gap-3 border-b bg-card p-4 sm:grid-cols-5">{[["From District","from","text"],["To District","to","text"],["Load (KG)","load","number"],["Freight (Rs/Kg)","freight","number"],["Reason","remarks","text"]].map(([label,name,type])=><label key={name}><small className="mb-1 block">{label}</small><input required={name!=="remarks"} type={type} step={type==="number"?"any":undefined} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})} className="h-10 w-full rounded border bg-white px-3"/></label>)}<button className="rounded bg-primary px-4 py-2 text-white sm:col-span-5">Save Rate</button></form>}
 <div className="p-3"><div className="relative mb-3"><Search className="absolute left-3 top-3 w-4"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search From, To or Load…" className="h-10 w-full rounded border pl-9"/></div><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-card"><tr>{["From","To","Load (KG)","Freight (Rs/Kg)","Source"].map(x=><th key={x} className="border p-2 text-left">{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="border p-2 font-medium">{r.from_district}</td><td className="border p-2 font-medium">{r.to_district}</td><td className="border p-2">{Number(r.quantity_kg).toLocaleString("en-IN")}</td><td className="border p-2">₹{r.base_freight_per_kg}</td><td className="border p-2">{r.source}</td></tr>)}</tbody></table>{!filtered.length&&<p className="p-6 text-center text-muted-foreground">No freight rates found.</p>}</div></div></section>
}
